apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn-fast-unreplicated-strictlocal
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-secret
