apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-s3
  namespace: monitoring
spec:
  refreshInterval: "30m"
  target:
    name: loki-s3
    creationPolicy: Owner
    template:
      data:
        access_key_id: "{{ .RUSTFS_ACCESS_KEY }}"
        secret_access_key: "{{ .RUSTFS_SECRET_KEY }}"
        AWS_ACCESS_KEY_ID: "{{ .RUSTFS_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .RUSTFS_SECRET_KEY }}"
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: rustfs
