apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-database
  namespace: flux-system
spec:
  path: "./cluster/apps/forgejo/database"
  targetNamespace: forgejo
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-app
  namespace: flux-system
spec:
  dependsOn:
    - name: forgejo-database
  path: "./cluster/apps/forgejo/app"
  targetNamespace: forgejo
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
