FROM nixos/nix:latest

ARG SOURCE_REPO="unknown"

LABEL org.opencontainers.image.title="nixos-build-daemon"
LABEL org.opencontainers.image.description="Nix build daemon container for remote builds."
LABEL org.opencontainers.image.source="${SOURCE_REPO}"

RUN nix --version \
    && nix-env -iA nixpkgs.openssh \
    && mkdir -p /etc/nix /nix/var/nix/daemon-socket /nix/var/nix/builds /cache-keys \
    && chown root:root /nix/var/nix/builds \
    && chmod 0755 /nix/var/nix/builds

COPY start-nix-daemon.sh /usr/local/bin/start-nix-daemon.sh
COPY nix-post-build-hook.sh /usr/local/bin/nix-post-build-hook.sh

RUN chmod 0755 /usr/local/bin/start-nix-daemon.sh /usr/local/bin/nix-post-build-hook.sh

VOLUME ["/nix"]

CMD ["/usr/local/bin/start-nix-daemon.sh"]
