{
 "title": "Crowdsec monitoring",
 "description": "CrowdSec monitoring dashboard with real-time insights on blocked pods, attack scenarios, banned IPs, and security decisions.",
 "tags": [
  "crowdsec",
  "waf",
  "prod & qa",
  "loki and prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus_Source", "query": "prometheus" },
   { "name": "query0", "label": "Loki_source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "block total for pods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cs_appsec_block_total", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "attacks by scenarios",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cs_alerts", "legendFormat": "{{reason}}" }
   ]
  },
  {
   "title": "Total ban by IP",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (cenario, ip) (\n  count_over_time(\n    {container=\"crowdsec-lapi\"} |~ \"alert\"\n    | regexp `alert : (?P<scenario>\\S+) by ip (?P<source_ip>\\S+)`\n    | label_format cenario=\"{{.scenario}}\", ip=\"{{.source_ip}}\"\n  [${__range}])\n)"
    }
   ]
  },
  {
   "title": "Decisions list",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"crowdsec-lapi\"} |= \"/v1/decisions?ip=\""
    }
   ]
  },
  {
   "title": "IPs that attempted malicious attacks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{container=\"crowdsec-lapi\"} |~ \"alert\" | regexp `alert : (?P<scenario>\\S+) by ip (?P<source_ip>\\S+)` | scenario != \"\" | line_format `cenario=\"{{.scenario}}\", ip=\"{{.source_ip}}\"`"
    }
   ]
  },
  {
   "title": "lapi_decisions_ko_total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_lapi_decisions_ko_total",
     "legendFormat": "Bouncer: {{bouncer}} | Instância: {{instance}}"
    }
   ]
  },
  {
   "title": "Requests per Bouncer Over Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "cs_lapi_route_requests_total",
     "legendFormat": "Bouncer: {{bouncer}} | Rota: {{route}}"
    }
   ]
  },
  {
   "title": "Total de request dos bouncers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(cs_lapi_bouncer_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}