FROM nixos/nix:latest

ARG SOURCE_REPO="unknown"

LABEL org.opencontainers.image.title="nixos-build-ssh-gateway"
LABEL org.opencontainers.image.description="SSH gateway container for a Nix build daemon."
LABEL org.opencontainers.image.source="${SOURCE_REPO}"

COPY nix-post-build-hook.sh /usr/local/bin/nix-post-build-hook.sh

RUN nix --version \
	&& nix-env -iA nixpkgs.gnused \
	&& mkdir -p /nix /var/empty /etc/ssh \
	&& cp -L /etc/passwd /tmp/passwd \
	&& cp -L /etc/group /tmp/group \
	&& cp -L /etc/shadow /tmp/shadow \
	&& rm -f /etc/passwd /etc/group /etc/shadow \
	&& mv /tmp/passwd /etc/passwd \
	&& mv /tmp/group /etc/group \
	&& mv /tmp/shadow /etc/shadow \
	&& (grep -q '^sshd:' /etc/passwd || printf '%s\n' 'sshd:x:74:74:sshd:/var/empty:/sbin/nologin' >> /etc/passwd) \
	&& (grep -q '^sshd:' /etc/group || printf '%s\n' 'sshd:x:74:' >> /etc/group) \
	&& /nix/var/nix/profiles/default/bin/sed -i 's/^root:!:/root::/' /etc/shadow \
	&& mkdir -p /usr/local/bin \
	&& printf '%s\n' \
	'#!/bin/sh' \
	'unset NIX_S3_BUCKET NIX_S3_ENDPOINT NIX_S3_REGION NIX_S3_SCHEME AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE' \
	'exec /nix/var/nix/profiles/default/bin/nix-store --store unix:///nix/var/nix/daemon-socket/socket "$@"' \
	> /usr/local/bin/nix-store \
	&& printf '%s\n' \
	'#!/bin/sh' \
	'unset NIX_S3_BUCKET NIX_S3_ENDPOINT NIX_S3_REGION NIX_S3_SCHEME AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_PROFILE' \
	'exec /nix/var/nix/profiles/default/bin/nix --store unix:///nix/var/nix/daemon-socket/socket "$@"' \
	> /usr/local/bin/nix \
	&& chmod 0755 /usr/local/bin/nix-store /usr/local/bin/nix /usr/local/bin/nix-post-build-hook.sh \
	&& printf '%s\n' \
	'Port 22' \
	'ListenAddress 0.0.0.0' \
	'Protocol 2' \
	'HostKey /ssh/ssh_host_rsa_key' \
	'HostKey /ssh/ssh_host_ed25519_key' \
	'PermitRootLogin prohibit-password' \
	'PubkeyAuthentication yes' \
	'PasswordAuthentication no' \
	'KbdInteractiveAuthentication no' \
	'ChallengeResponseAuthentication no' \
	'UsePAM no' \
	'AllowTcpForwarding yes' \
	'X11Forwarding no' \
	'PrintMotd no' \
	'SetEnv PATH=/usr/local/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin' \
	'SetEnv NIX_REMOTE=unix:///nix/var/nix/daemon-socket/socket' \
	'Subsystem sftp /nix/var/nix/profiles/default/libexec/sftp-server' \
	'AuthorizedKeysFile /ssh/authorized_keys' \
	'PidFile /ssh/sshd.pid' \
	> /etc/ssh/sshd_config

EXPOSE 22

ENV HOME=/root \
    AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials \
    AWS_CONFIG_FILE=/root/.aws/config \
    AWS_SDK_LOAD_CONFIG=1 \
    AWS_EC2_METADATA_DISABLED=true

VOLUME ["/nix", "/ssh"]

CMD ["/bin/sh", "-c", "exec /nix/var/nix/profiles/default/bin/sshd -D -e -f /etc/ssh/sshd_config"]
