apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec
resources:
  - ./postgres-cluster.yaml
  - ./postgres-externalsecret.yaml
  - ./secrets-externalsecret.yaml
  - ./helmrelease.yaml
  - ./virtualservice.yaml
