apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-db-secret
  namespace: crowdsec
spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
  target:
    name: crowdsec-db-secret
    template:
      data:
        username: "crowdsec"
        password: "{{ .db_password }}"
  dataFrom:
    - extract:
        key: crowdsec
