# =============================================================================
# Auto-generated import blocks
# Generated by: scripts/opnsense_import.sh
#
# After reviewing, run:
#   terraform plan -generate-config-out=generated.tf
#   terraform apply
# =============================================================================

import {
  to = opnsense_firewall_alias.bogons
  id = "bogons"
}

import {
  to = opnsense_firewall_alias.bogonsv6
  id = "bogonsv6"
}

import {
  to = opnsense_firewall_alias.servernet
  id = "269d5ef0-5d26-4c21-be9a-4c4d527645e2"
}

import {
  to = opnsense_firewall_alias.sshlockout
  id = "sshlockout"
}

import {
  to = opnsense_firewall_alias.virusprot
  id = "virusprot"
}

import {
  to = opnsense_firewall_alias.wan_network
  id = "4e29bf97-2278-4a82-9fa2-27d927a1dc96"
}

import {
  to = opnsense_firewall_alias.wifi
  id = "f83df8ca-a0e6-4cf5-9bc5-8287b89f73f5"
}

import {
  to = opnsense_firewall_alias.lo0_network
  id = "__lo0_network"
}

import {
  to = opnsense_firewall_alias.opt1_network
  id = "__opt1_network"
}

import {
  to = opnsense_firewall_alias.opt2_network
  id = "__opt2_network"
}

import {
  to = opnsense_firewall_alias.opt3_network
  id = "__opt3_network"
}

import {
  to = opnsense_firewall_alias.wan_network_1
  id = "__wan_network"
}

import {
  to = opnsense_firewall_alias.wireguard_network
  id = "__wireguard_network"
}

import {
  to = opnsense_route.route_192_168_84_0_24
  id = "a8e5c766-5a86-46aa-83fe-26c32486e74d"
}

import {
  to = opnsense_route.route_192_168_87_0_24
  id = "cbca752b-46e3-4a17-bf04-3539e434abb5"
}

import {
  to = opnsense_route.route_10_10_10_0_24
  id = "defb5942-580f-4350-9937-ea9c2fe15b36"
}

import {
  to = opnsense_wireguard_server.wg_server_princessbelongsto_me
  id = "cfbd90bc-9069-4116-8d83-247abe8a4f8d"
}

import {
  to = opnsense_wireguard_client.wg_client_edge
  id = "b1ba1bf2-f3a7-4fd0-8dcf-d548637b2cf9"
}

