apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lore
  namespace: lore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast-unreplicated
  resources:
    requests:
      storage: 400Gi
