#!/usr/bin/env bash
# =============================================================================
# scripts/opnsense_import.sh
#
# Queries the OPNsense API for all existing resources (firewall, interfaces,
# routes, wireguard) and generates Terraform import blocks + auto-generated
# resource config using: terraform plan -generate-config-out=generated.tf
#
# Prerequisites: Run inside nix-shell with terraform, jq, curl
# Usage: nix-shell -p terraform jq curl --run "bash scripts/opnsense_import.sh"
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OPNSENSE_DIR="$SCRIPT_DIR/../terraform/opnsense"

cd "$OPNSENSE_DIR"

# ---------------------------------------------------------------------------
# 1. Read OPNsense credentials directly from .auto.tfvars
# ---------------------------------------------------------------------------
OPNSENSE_API_KEY=$(grep 'OPNSENSE_API_KEY' .auto.tfvars | sed 's/.*= *"\(.*\)"/\1/')
OPNSENSE_API_SECRET=$(grep 'OPNSENSE_API_SECRET' .auto.tfvars | sed 's/.*= *"\(.*\)"/\1/')
OPNSENSE_ROUTER_IP=$(grep 'OPNSENSE_ROUTER_IP' .auto.tfvars | sed 's/.*= *"\(.*\)"/\1/')

API_BASE="https://${OPNSENSE_ROUTER_IP}"
API_CREDS="${OPNSENSE_API_KEY}:${OPNSENSE_API_SECRET}"

echo "==> OPNsense credentials loaded from .auto.tfvars"
echo "    Router IP : ${OPNSENSE_ROUTER_IP}"
echo "    API URI   : ${API_BASE}"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Query OPNsense API (POST with pagination disabled → all rows)
query_api() {
  local endpoint="$1"
  curl -sk -u "$API_CREDS" \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"current":1,"rowCount":-1,"searchPhrase":""}' \
    "${API_BASE}${endpoint}" 2>/dev/null
}

# Sanitize a name into a valid Terraform identifier
sanitize_name() {
  echo "$1" | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9_]/_/g' \
    | sed 's/__*/_/g' \
    | sed 's/^_//' \
    | sed 's/_$//' \
    | sed 's/^$/unnamed/'
}

# ---------------------------------------------------------------------------
# 2. Query OPNsense API and generate import blocks
# ---------------------------------------------------------------------------
echo ""
echo "==> Querying OPNsense API for existing resources..."

IMPORTS_FILE="imports.tf"
> "$IMPORTS_FILE"

cat >> "$IMPORTS_FILE" <<'EOF'
# =============================================================================
# Auto-generated import blocks
# Generated by: scripts/opnsense_import.sh
#
# After reviewing, run:
#   terraform plan -generate-config-out=generated.tf
#   terraform apply
# =============================================================================

EOF

IMPORT_COUNT=0

# Use a temp file to track seen names (avoids subshell variable scoping issues)
SEEN_FILE=$(mktemp)
trap 'rm -f "$SEEN_FILE"' EXIT

# Sanitize a name into a valid Terraform identifier
sanitize_name() {
  echo "$1" | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9_]/_/g' \
    | sed 's/__*/_/g' \
    | sed 's/^_//' \
    | sed 's/_$//' \
    | sed 's/^$/unnamed/'
}

# Ensure unique resource names; sets UNIQUE_RESULT global variable
unique_name() {
  local base="$1"
  local candidate="$base"
  local i=1
  while grep -qw "$candidate" "$SEEN_FILE" 2>/dev/null; do
    candidate="${base}_${i}"
    i=$((i + 1))
  done
  echo "$candidate" >> "$SEEN_FILE"
  UNIQUE_RESULT="$candidate"
}

# ---- Firewall Aliases ----
echo "  -> Firewall aliases..."
ALIASES_JSON=$(query_api "/api/firewall/alias/searchItem")
ALIASES=$(echo "$ALIASES_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.name)"' 2>/dev/null || true)
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  unique_name "$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_firewall_alias.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
done <<< "$ALIASES"

# ---- Firewall Categories ----
echo "  -> Firewall categories..."
CATEGORIES_JSON=$(query_api "/api/firewall/category/searchItem")
CATEGORIES=$(echo "$CATEGORIES_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.name)"' 2>/dev/null || true)
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  unique_name "cat_$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_firewall_category.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
done <<< "$CATEGORIES"

# ---- Firewall Filter Rules ----
echo "  -> Firewall filter rules..."
FILTERS_JSON=$(query_api "/api/firewall/filter/searchRule")
FILTERS=$(echo "$FILTERS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.description // "")"' 2>/dev/null || true)
FILTER_IDX=0
while IFS='|' read -r uuid desc; do
  [ -z "$uuid" ] && continue
  if [ -n "$desc" ] && [ "$desc" != "null" ]; then
    unique_name "filter_$(sanitize_name "$desc")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "filter_rule_${FILTER_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_firewall_filter.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  FILTER_IDX=$((FILTER_IDX + 1))
done <<< "$FILTERS"

# ---- Firewall NAT (Source NAT) ----
echo "  -> Firewall NAT rules..."
NATS_JSON=$(query_api "/api/firewall/source_nat/searchRule")
NATS=$(echo "$NATS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.description // "")"' 2>/dev/null || true)
NAT_IDX=0
while IFS='|' read -r uuid desc; do
  [ -z "$uuid" ] && continue
  if [ -n "$desc" ] && [ "$desc" != "null" ]; then
    unique_name "nat_$(sanitize_name "$desc")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "nat_rule_${NAT_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_firewall_nat.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  NAT_IDX=$((NAT_IDX + 1))
done <<< "$NATS"

# ---- Interfaces VLANs ----
echo "  -> Interface VLANs..."
VLANS_JSON=$(query_api "/api/interfaces/vlan_settings/searchItem")
VLANS=$(echo "$VLANS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.vlanif // .description // "")"' 2>/dev/null || true)
VLAN_IDX=0
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  if [ -n "$name" ] && [ "$name" != "null" ]; then
    unique_name "vlan_$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "vlan_${VLAN_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_interfaces_vlan.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  VLAN_IDX=$((VLAN_IDX + 1))
done <<< "$VLANS"

# ---- Interfaces VIPs ----
echo "  -> Interface Virtual IPs..."
VIPS_JSON=$(query_api "/api/interfaces/vip_settings/searchItem")
VIPS=$(echo "$VIPS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.subnet // .address // "")"' 2>/dev/null || true)
VIP_IDX=0
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  if [ -n "$name" ] && [ "$name" != "null" ]; then
    unique_name "vip_$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "vip_${VIP_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_interfaces_vip.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  VIP_IDX=$((VIP_IDX + 1))
done <<< "$VIPS"

# ---- Routes ----
echo "  -> Static routes..."
ROUTES_JSON=$(query_api "/api/routes/routes/searchroute")
ROUTES=$(echo "$ROUTES_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.network // "")"' 2>/dev/null || true)
ROUTE_IDX=0
while IFS='|' read -r uuid network; do
  [ -z "$uuid" ] && continue
  if [ -n "$network" ] && [ "$network" != "null" ]; then
    unique_name "route_$(sanitize_name "$network")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "route_${ROUTE_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_route.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  ROUTE_IDX=$((ROUTE_IDX + 1))
done <<< "$ROUTES"

# ---- WireGuard Servers ----
echo "  -> WireGuard servers..."
WG_SERVERS_JSON=$(query_api "/api/wireguard/server/searchServer")
WG_SERVERS=$(echo "$WG_SERVERS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.name // "")"' 2>/dev/null || true)
WG_SRV_IDX=0
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  if [ -n "$name" ] && [ "$name" != "null" ]; then
    unique_name "wg_server_$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "wg_server_${WG_SRV_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_wireguard_server.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  WG_SRV_IDX=$((WG_SRV_IDX + 1))
done <<< "$WG_SERVERS"

# ---- WireGuard Clients (Peers) ----
echo "  -> WireGuard clients..."
WG_CLIENTS_JSON=$(query_api "/api/wireguard/client/searchClient")
WG_CLIENTS=$(echo "$WG_CLIENTS_JSON" | jq -r '.rows[]? | "\(.uuid)|\(.name // "")"' 2>/dev/null || true)
WG_CLI_IDX=0
while IFS='|' read -r uuid name; do
  [ -z "$uuid" ] && continue
  if [ -n "$name" ] && [ "$name" != "null" ]; then
    unique_name "wg_client_$(sanitize_name "$name")"
  safe_name="$UNIQUE_RESULT"
  else
    unique_name "wg_client_${WG_CLI_IDX}"
  safe_name="$UNIQUE_RESULT"
  fi
  cat >> "$IMPORTS_FILE" <<EOF
import {
  to = opnsense_wireguard_client.${safe_name}
  id = "${uuid}"
}

EOF
  IMPORT_COUNT=$((IMPORT_COUNT + 1))
  WG_CLI_IDX=$((WG_CLI_IDX + 1))
done <<< "$WG_CLIENTS"

# ---------------------------------------------------------------------------
# 3. Summary & terraform init + plan
# ---------------------------------------------------------------------------
echo ""
echo "==> Generated ${IMPORT_COUNT} import blocks in ${IMPORTS_FILE}"

if [ "$IMPORT_COUNT" -eq 0 ]; then
  echo ""
  echo "WARNING: No resources found. Check OPNsense API connectivity."
  echo "  Test with: curl -sk -u '<key>:<secret>' ${API_BASE}/api/core/firmware/status"
  exit 1
fi

echo ""
echo "==> Running terraform init..."
terraform init

echo ""
echo "==> Generating resource config from import blocks..."
echo "    terraform plan -generate-config-out=generated.tf"
echo ""

# Remove any prior generated.tf so the flag doesn't error
rm -f generated.tf

terraform plan -generate-config-out=generated.tf || true

echo ""
echo "============================================================"
echo "  DONE!"
echo ""
echo "  Review the generated files:"
echo "    ${OPNSENSE_DIR}/imports.tf     – import blocks"
echo "    ${OPNSENSE_DIR}/generated.tf   – auto-generated resource config"
echo ""
echo "  Once satisfied, run:"
echo "    cd ${OPNSENSE_DIR}"
echo "    terraform apply"
echo "============================================================"
