---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pdns
  namespace: external-dns
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    provider:
      name: pdns
    env:
      - name: EXTERNAL_DNS_PDNS_API_KEY
        valueFrom:
          secretKeyRef:
            name: &secret pdns-api-key
            key: api_key
    extraArgs:
      - --pdns-server=http://192.168.88.1:8081
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --label-filter=external-dns/provider=pdns
      - --events
      - --ignore-ingress-tls-spec
    policy: sync
    sources: ["crd"]
    txtPrefix: pdns.
    txtOwnerId: pdns
    txtWildcardReplacement: wildcard
    domainFilters:
      - ${domain_name}
    serviceMonitor:
      enabled: true
