apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pdns-api-key
  namespace: external-dns
spec:
  refreshInterval: "30m"
  target:
    name: pdns-api-key
    creationPolicy: Owner
    template:
      data:
        api_key: "{{ .api_key }}"
  dataFrom:
  - extract:
      key: pdns
  secretStoreRef:
    name: global-secret-store
    kind: ClusterSecretStore
